name: iOS TestFlight

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.6'

      - name: Flutter version
        run: flutter --version

      - name: Dart version
        run: dart --version

      - name: Flutter pub get
        run: flutter pub get

      - name: Analyze
        run: dart analyze .